dist: trusty
sudo: false
language: ruby
rvm:
- 2.2.2
cache: bundler
script:
- bundle exec jekyll build
- bundle exec htmlproofer --assume-extension --check-html --disable-external ./_site
  --file-ignore /lectures/f16/,/lectures/w17/,/lectures/f17/,/lectures/w18/,/archive/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: LlCVlH+acLKwi+U6o9Idi4irUWmhx2vKtKE7pBPpmKOaou1VbkyLga+/dJpjG8nHpxz7T1G/XeInXWJInJ0SzBKTFAe/XdHERFfdgvXAnTxJFjjU9Udd4HyVPuDap/cx7VfrOoHvpq6dQseaHFhn/RByY5aMGqH4Hqkie2ifyN+3+ieIaYSy5HJSTsSHuDMZsXlDjjRbmG5r3fnt+i2oxaLA5nFUmPt0/kAAIiTdFp1tvt8TrR5oqXa1VZWwW7FM3i0uWPbW6z82q/be/ZcSMLyXy/mCpDDjolqx/KIj91uwvq5TmrcqNO9fROjc5KUnkM3+JAvATbiwWXqOWTygTkZYJnwVKuXwhxg71pWNReCEgR52nz6Du5KXwMnhjtJkpaulpfm0eZFm/Ya2naZK1unvJFE/4bPdxms04R+vEGrpJIQ+OdDcjLvfQN+etE4qL7VyjuGk8zZSOmsNt38lo3hRvTeJm9zJ1rce3V0xxkqmQRDSVN0x2hZF56+rt69U56ghuuLeCuNsAS0Io7yc4m9XWNtyBKJ079hqQq3CXGB9hmvPY2wGk2NUXn/oddKEKuJ1ZHxPkuSmTGjTAST7cGl6ytvxkGjBx3VmEIWQlXUTRVTp+NjReXAr8Gojo0X/V4HOTGj83yjTvyA6BKFUD/eDfkHZU97n+yo5EVFv/Us=
  email:
    recipients:
    - c4cs-staff@umich.edu
