dist: trusty
sudo: false

language: ruby
rvm:
  - 2.2.2
cache: bundler

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension --check-html --url-ignore '/.*docs.google.com/a/umich.edu.*/' ./_site --file-ignore curl.md

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

