dist: trusty
sudo: false

language: ruby
rvm:
  - 2.1
cache: bundler

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension --check-html --url-ignore '/.*docs.google.com/a/umich.edu.*/' ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

